# Generated by Django 3.0.8 on 2021-01-07 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sheets', 'SHEETS'), ('components', 'COMPONENTS'), ('liquids', 'LIQUIDS'), ('lengths', 'LENGTHS')], default='sheets', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='diameter',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
