# Generated by Django 3.0.8 on 2021-01-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210114_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='area',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
