# Generated by Django 3.0.8 on 2021-02-02 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='diameter',
        ),
    ]
