# Generated by Django 3.0.8 on 2021-02-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20210211_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='area',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='calculated_cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
