# Generated by Django 3.0.8 on 2021-02-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20210212_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
